export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL'

export const PURCHASE_BURGUER_SUCCESS = 'PURCHASE_BURGUER_SUCCESS'
export const PURCHASE_BURGUER_FAIL = 'PURCHASE_BURGUER_FAIL'
